workspace:
  base: /go
  path: src/github.com/EVE-Tools/static-data

pipeline:
  build:
    image: golang:alpine
    commands:
      - apk update
      - apk add git
      - go get ./...
      - go build

  docker:
    image: plugins/docker
    repo: evetools/static-data
    secrets: [ docker_username, docker_password ]
    tag:
      - latest
      - ${DRONE_BRANCH}